services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: radiant
      POSTGRES_PASSWORD: radiant123
      POSTGRES_DB: radiant_graph
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://radiant:radiant123@postgres:5432/radiant_graph
    depends_on:
      - postgres

volumes:
  postgres_data:
